"""
This script will delete all the logs generated by running the model.

Args: 
    a : (ALL)Will delete all log files
    s : (SELECT) will delete logs of particular kind. Requires additional 4 boolean arguments 
        to select logs to delete. 
        1: Run logs
        2: Fitness curve of each runs
        3: Exported fitness curve graphs
        4: Dataset benchmark records

        example : python clean_logs.py s True False False False

"""

import os 
import sys


def records():
    for records in os.listdir("./logs/"):
        if records.endswith('.csv'):
            t = "./logs/"+records
            os.unlink(t)

def log():
    for log in os.listdir("./logs/test_log/"):
        if log.endswith('.log'):
            s = "./logs/test_log/"+log
            os.unlink(s)

def curve():
    for curve in os.listdir("./logs/output_curve/"):
        if (curve.endswith('.png') or curve.endswith('.svg')):
            y = "./logs/output_curve/"+curve
            os.unlink(y)

def genfit():
    for genfit in os.listdir("./logs/curve_log/"):
        if genfit.endswith('.csv'):
            j = "./logs/curve_log/"+genfit
            os.unlink(j)


if(len(sys.argv) == 2 or len(sys.argv) == 6):
    if(sys.argv[1] == 'a'):
        print("Cleaned all logs")
        records()
        log()
        curve()
        genfit()

    elif(sys.argv[1] == 's' and len(sys.argv) == 6 ):
        if (sys.argv[2] == 'True'):
            print("Cleaned run logs")
            log()
        if (sys.argv[3] == 'True'):
            print("Cleaned generation fitness logs")
            genfit()
        if (sys.argv[4] == 'True'):
            print("Deleted curve exports")
            curve()
        if (sys.argv[5] == 'True'):
            print("Cleaned record logs")
            records()

else:
    print("Invalid argument")
    sys.exit()
    